version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: petlove-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: petlove123
      MONGO_INITDB_DATABASE: petlove
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - petlove-network

  # PetLove Application (Frontend + Backend)
  petlove-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petlove-app
    restart: unless-stopped
    environment:
      - PORT=8000
      - MONGODB_URI=mongodb://admin:petlove123@mongodb:27017/petlove?authSource=admin
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - petlove-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    driver: local

networks:
  petlove-network:
    driver: bridge
